//
// Created by Connor on 8/24/2025.
//
#ifndef METALHEADPINS_H
#define METALHEADPINS_H

// Outputs
#define SHEAR_CUT_PIN 22
#define SHEAR_HOME_PIN 23
#define TOOL_OUT_PIN 24
#define TOOL_IN_PIN 25
#define FEED_FORWARD_PIN 26
#define FEED_REVERSE_PIN 27
#define HEAD_CW_PIN 28
#define HEAD_CCW_PIN 29
#define HEAD_OUT_PIN 30
#define HEAD_IN_PIN 31

// Inputs/Interrupts
#define ENCODER_FEED_SET_PIN 32
#define ENCODER_FEED_RESET_PIN 33
#define ENCODER_BEND_SET_PIN 34
#define ENCODER_BEND_RESET_PIN 35
#define PROXIMITY_HEAD_OUT_PIN 36
#define PROXIMITY_HEAD_IN_PIN 37
#define PROXIMITY_SHEAR_HOME_PIN 38
#define PROXIMITY_SHEAR_CUT_PIN 39
#define PROXIMITY_TOOL_IN_PIN 40
#define PROXIMITY_TOOL_OUT_PIN 41
#define SHEAR_BUTTON_PIN 42
#define PROXIMITY_HEAD_LIMIT_PIN 43
#define PROXIMITY_HEAD_CW_PIN 44
#define PROXIMITY_HEAD_CCW_PIN 45
#define AUTO_BUTTON_PIN 46
#define ESTOP_PIN 47
#define FUSE_PIN 48

// HMI
#define HMI_TX_PIN 18
#define HMI_RX_PIN 19

// Power Monitors
#define TWENTY_FOUR_V_RAW_PIN 49
#define AUX_TWENTY_FOUR_V_PIN 50

#endif //METALHEADPINS_H